#!/usr/bin/python3
# -*- coding: utf-8 -*-

import re
class vehicule:  # on crée une classe vehicule qui est définie par 2 attributs à savoir MARQUE (make) & COULEUR (color)
    def __init__(self, make=0):
        self.make = make


    # valeur des deux attributs
    # make = ["Ford", "Renault", "Peugeot", "Volkswagen", "Opel"]
    # color = ["Black", "Blue", "Grey", "Red", "Tan"]


@@q1@@